### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by gongjing1996** [tiancheng-zhi/cs-stereo#1]
Hello,I have run this demo with command "CUDA_VISIBLE_DEVICES=1,0 python test.py --ckpt-path ckpt/47.pth"in win10.But there is an error:
File "D:\CrossStereo\cs-stereo\dataset.py", line 26, in __init__
    rgb_exp = float(splited[2])
IndexError: list index out of range
I know it aims to extract contents of the file,but the intermediate result is like this "['20170222_0951', '220951_061756']".So I don't know how to get "rgb_exp = float(splited[2])
                nir_exp = float(splited[3])".

**Comment by tiancheng-zhi** [comment]
Hi, you may wanna use the "data" and "lists" from "Stereo Matching Data" rather than "Material Segmentation Data".
download here: https://drive.google.com/file/d/1ikj7UcnQsdxUfDF5EI3YcFK-p63KHQmy/view
