### ISSUE TITLE
what't the meaning of exp_retio?

### ISSUE THREAD

**Issue by cswwp** [tiancheng-zhi/cs-stereo#2]
Hi, really thanks for sharing,  i'm confused about exp_retio, what't the meaning of exp_retio? Do you mind explain? @tiancheng-zhi

**Comment by tiancheng-zhi** [comment]
Hi, exp_ratio is the ratio between NIR exposure time and RGB exposure time. Please see Equation 5 in the paper. It should not matter much since the data were captured with auto-exposure.
